### ISSUE TITLE
About raw results

### ISSUE THREAD

**Issue by soledad921** [facebookresearch/kbc#6]
Hi, could you explain how to get raw ranks of testing example?

**Comment by timlacroix** [comment]
Hi,

I won't add that functionality in the code, but you can hack it in by changing datasets.big.getToSkip()

if the skip lists are empty, I believe you should be able to get unfiltered metrics.
Then if you want mean rank rather than mean reciprocal rank, you can change l.86 of datasets.big.do_eval and remove the 1. / ranks

Thanks for your interest !

**Comment by soledad921** [comment]
> Hi,
> 
> I won't add that functionality in the code, but you can hack it in by changing datasets.big.getToSkip()
> 
> if the skip lists are empty, I believe you should be able to get unfiltered metrics.
> Then if you want mean rank rather than mean reciprocal rank, you can change l.86 of datasets.big.do_eval and remove the 1. / ranks
> 
> Thanks for your interest !

Thanks for your time and answering!
